### ISSUE TITLE
Why is necessary to disable the battery optimizations?

### ISSUE THREAD

**Issue by avecina** [DP-3T/dp3t-sdk-android#199]
https://github.com/DP-3T/dp3t-sdk-android/blob/a47fdadcdcc1a7acbd3d08f36eafc553751c8900/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/ErrorHelper.java#L72

Why is necessary to disable the battery optimizations? Is part of the google sdk requirements? It's more about curiosity, but there are tons of users complaining about this.

Thanks.

**Comment by simonroesch** [comment]
Disabling battery optimizations is needed to improve the reliability of the androidx WorkManager. If we would not disable this, this could lead to the SwissCovid app being affected by [App Standby](https://developer.android.com/training/monitoring-device-state/doze-standby#understand_app_standby) (because normally users don't open the app frequently) and thus the WorkManager jobs might be delayed several hours, which in return leads to late alerts. With disabling battery optimization we prevent our app from being affected by App Standby.
