### ISSUE TITLE
Onset dates mismatch

### ISSUE THREAD

**Issue by l-maia** [DP-3T/dp3t-sdk-android#37]
The android devices use the current day as the onset, while IOS devices set the onset to a previous date.
This is an example from our test database:

| pk_exposed_id | key | received_at |   onset    |      app_source |
| ------------- |:-------------:| :-------------:| :-------------:| :-------------:|
| 38 | LUZv5MNyZRc+TBBUA7Z9w1476mjOW7ZYoYlYVe7v4RY= | 2020-04-22 10:38:35.280914+00 | 2020-04-22 | demo |
| 39 | gxBppVMfpHB4pTHadpnlidAEucYrpeNUlJHse5dZkyU= | 2020-04-22 12:19:06.404572+00 | 2020-04-08 | demo|

The ID 38 was set by android and 39 was set by IOS.

**Comment by Vanuan** [comment]
Shouldn't onset be a user-provided date?

**Comment by l-maia** [comment]
Not sure, i believe that this onset refers to the crypto key and not the infection thus containing the date the key was being used in the crypto protocol and being treated as an epoch.

If that is the case, the IOS sdk is the buggy implementation .

**Comment by simonroesch** [comment]
The onset date has to be provided by the app including the SDK (either by user input or some medical country-specific system). The onset date defines the date from which the infected person was starting to infect other people. Therefore the SK of the onset date will be published (and from this SK you can derive the SKs of the following days). If the onset date is before the first date of an SK (because the app was not yet installed then) the first available SK will be published. 

I hope this explains your concernes.

**Comment by l-maia** [comment]
Then the Android SDK does not send the correct date as the onset to the server.

Thus when you return the date from the last entry you should use the onset date, not the last entry date.

**Comment by simonroesch** [comment]
Ah, now I understand your point. The naming is misleading here. The onset date sent to the server does not have to be the actual onset date, but must be the date the sent SK was actually used. Otherwise the matching would fail in the end, because we check the SK of a day only with the ephIDs we received on that day.

**Comment by stmitt** [comment]
@l-maia  I just discovered that the iOS client isn't sending the correct onset date. This will be fixed soon.

**Comment by l-maia** [comment]
Ok.  So the IOS implementation is wrong because it always send the currentdate-15 ignoring the date of the key.
Thus always failing the comparison.

**Comment by simonroesch** [comment]
You are correct! Thank you very much for pointing this out!
