### ISSUE TITLE
Question about handshakes

### ISSUE THREAD

**Issue by cpepi001** [DP-3T/dp3t-sdk-android#89]
I've let the Calibration app to run for one hour in two phones. I've placed the phones next to each other and without any other Bluetooth device nearby.

Both phones have 4 contacts. So this mean if we are close to each other >= 15 minutes a contact is created. Correct?

Now, 2913 is the total amount of handshakes in one phone and the 2nd phone has 332 handshakes.
This difference is because of hardware?

**Comment by zukunft** [comment]
The version 0.2.6 is running since a 8.5.2020 on several phones with normal usage. The number of handshakes are around 13'000 and the number of contacts around 200. The battery usage seems to be between 3 and 6%. What happens in case of a battery shortage? Maybe the app should start to scan less to prevent a complete shutdown due to missing energy.

**Comment by cpepi001** [comment]
@zukunft 
Did you try the "Report Infected" (supposed a contact was created) and received notification?

I tried with DP3T demo and it works but not with Calibration app
